apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crud-app-deployment-frontend
  labels:
    app: my-crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-crud-app
  template:
    metadata:
      labels:
        app: my-crud-app
    spec:
      containers:
        - name: my-crud-app-container
          image: 17b132se/my-crud-app-frontend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: frontend-configmap
