apiVersion: v1
kind: Service
metadata:
  name: my-crud-app-backend-service
spec:
  selector:
    app: my-crud-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer

